services:
  # Tu aplicación Node.js (Lockus)
  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    networks:
      - jenkins_network

  # Base de datos Mongo
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    networks:
      - jenkins_network

  # Jenkins principal
  jenkins:
    build:
      context: ./jenkins
      dockerfile: Dockerfile.jenkins
    container_name: jenkins
    privileged: true
    user: root
    ports:
      - "8090:8080"
      - "50000:50000"
    
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - jenkins_network
    environment:
      - JENKINS_OPTS=--prefix=/jenkins

  # Agente Jenkins 1
  jenkins-agent-1:
    image: jenkins/inbound-agent:latest
    container_name: jenkins-agent-1
    user: root
    privileged: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - jenkins_agent_1_home:/home/jenkins/agent
    environment:
      - JENKINS_URL=http://jenkins:8080/jenkins
      - JENKINS_AGENT_NAME=agent1
      - JENKINS_SECRET=agent1_secret
    networks:
      - jenkins_network
    depends_on:
      - jenkins

  # Agente Jenkins 2
  jenkins-agent-2:
    image: jenkins/inbound-agent:latest
    container_name: jenkins-agent-2
    user: root
    privileged: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - jenkins_agent_2_home:/home/jenkins/agent
    environment:
      - JENKINS_URL=http://jenkins:8080/jenkins
      - JENKINS_AGENT_NAME=agent2
      - JENKINS_SECRET=agent2_secret
    networks:
      - jenkins_network
    depends_on:
      - jenkins

  # Servidor Ubuntu de despliegue
  ubuntu-docker:
    build:
      context: ./ubuntu-docker
      dockerfile: Dockerfile
    container_name: ubuntu-docker
    privileged: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - jenkins_network
    ports:
      - "2222:22"
    restart: unless-stopped

networks:
  jenkins_network:
    driver: bridge

volumes:
  jenkins_home:
  jenkins_agent_1_home:
  jenkins_agent_2_home:
  app_deployment:
