FROM jenkins/jenkins:lts

USER root

# Instala herramientas necesarias (sin docker.io por ahora)
RUN apt-get update && \
    apt-get install -y sudo git curl python3 python3-pip && \
    pip3 install locust && \
    usermod -aG docker jenkins && \
    echo "jenkins ALL=NOPASSWD: ALL" >> /etc/sudoers

    # No se incluye ninguna línea que use /var/run/docker.sock en build time
    # porque este socket solo existe cuando el contenedor está en ejecución
    
USER jenkins
